export const IMPORT_FILE = "IMPORT_FILE";
export const CHANGE_FILE = "CHANGE_FILE";

export const SHOW_EXPORT_MODAL = "SHOW_EXPORT_MODAL";
export const SHOW_IMPORT_MODAL = "SHOW_IMPORT_MODAL";
export const HIDE_EXPORT_MODAL = "HIDE_EXPORT_MODAL";
export const HIDE_IMPORT_MODAL = "HIDE_IMPORT_MODAL";

export const TOGGLE_FILTERS = "TOGGLE_FILTERS";

export const EDIT = "EDIT";
export const DELETE = "DELETE";
